# Generated by Django 5.1 on 2024-09-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img_url',
            field=models.ImageField(blank=True, null=True, upload_to='user/images'),
        ),
    ]
