# Generated by Django 5.1 on 2024-09-06 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('security_question_ans', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_authentication',
            },
        ),
    ]
